### ISSUE TITLE
animals

### ISSUE THREAD

**Issue by looonytoonz** [ebayShopper/ESSV3#4]
i rebuilt a new test server today... saved this mod for last... everything working the whole way... install this and then ***POOOF*** only animal that will spawn is one lone rabbit....?

**Comment by looonytoonz** [comment]
also upon rolling back to the last backup just prior to adding this mod does not return my animals.....

**Comment by looonytoonz** [comment]
even with only the epoch testkit and ESSv3 installed on a fresh built server i have no animals

**Comment by ebayShopper** [comment]
I just tested and animals spawn fine with ESSV3 installed, both after normal relog and fresh spawn. They do not spawn instantly. You have to wait a few minutes after login and check again.

As I said on discord, the problem is your server is not stock. GTX modifies the mission file and server pbo. You showed me they are using an incorrect version of variables.sqf which does not have `dayz_maxGlobalAnimals` defined. I don't know what other variables they left undefined or other mistakes they made.

Hosts should not be changing the mission file or dayz_server. This is one of the reasons managed hosts are usually a poor choice. I suggest getting a VPS or dedi and installing from scratch.
